function [fitresult, gof] = createFit(Flow_all, Pres_all, Powr_all)
%CREATEFIT(FLOW_ALL,PRES_ALL,POWR_ALL)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Flow_all
%      Y Input : Pres_all
%      Z Output: Powr_all
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-May-2018 01:30:27


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( Flow_all, Pres_all, Powr_all );

% Set up fittype and options.
ft = fittype( 'poly32' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'Power vs Flow, Pres' );
plot( fitresult, [xData, yData], zData);
% Label axes
xlabel('Flow [$\frac{m^3}{h}$]','Interpreter','latex');
ylabel('Pressure[bar]', 'Interpreter', 'latex');
zlabel('Power COnsumption', 'Interpreter', 'latex');
grid off
view( -2.3, 36.4 );


